### ISSUE TITLE
Pending registration email has link to info@thatcamp.org

### ISSUE THREAD

**Issue by patrickmj** [chnm/thatcamp-org#123]
The (default?) email that's sent for a pending registration includes a link to email info@thatcamp.org for any questions.

If I remember right, that's deprecated at best. Awesome magic would be to dig up the email of the organizer and stuff it into the email, but that sounds complicated and/or impossible.

This comes from THATCamp New Souths registration, which seems to be splitting the info and operations between the thatcamp site and http://www.library.vcu.edu/about/events/2015-16/thatcamp-new-souths-2016.html, which is a complicating factor.

**Comment by boonebgorges** [comment]
It's definitely not impossible to swap out the email address, and 
probably isn't too complicated. Can you briefly spell out the details of 
the worflow here? I've forgotten how these registrations work. Are they 
originating from thatcamp.org, or from the specific THATCamp site? What 
is the text of the email being sent? (will help me grep the codebase)

**Comment by patrickmj** [comment]
What I got is

```
Your registration form for Sample THATCamp Site has been received. You will receive another e-mail when your registration has been approved. Please contact info@thatcamp.org with any questions.
```

which makes clear that they haven't done anything to build up their site (also clear from the site itself, http://newsouths2016.thatcamp.org/ )

I, too, have forgotten that workflow. I suspect that it's default text that we expect people to change in building up their sites, but if the sites aren't built out, that's some option for the site, that has that text included in the clone of the sample site.

**Comment by boonebgorges** [comment]
Ah, gotcha.

>  I suspect that it's default text that we expect people to change in building up their sites, but if the sites aren't built out, that's some option for the site, that has that text included in the clone of the sample site.

Yes, this looks correct. See https://github.com/chnm/thatcamp-org/blob/610e7e3361a1a4ec9e489b05b7e9ba4a24572d92/wp-content/plugins/thatcamp-registrations/thatcamp-registrations-functions.php#L578. `get_option( 'admin_email' )` will fetch the email address of the *local site admin*. If `info@thatcamp.org` is showing up instead, it means that the site has not yet been set up with the proper admin email address. 

It's hard to know without further testing (and I don't seem to have a working clone of the site at the moment), but it could be that we can be a bit smarter at setting the default 'admin_email' during site generation. At the following point https://github.com/chnm/thatcamp-org/blob/610e7e3361a1a4ec9e489b05b7e9ba4a24572d92/wp-content/themes/thatcamp-karma/functions.php#L907, insert this:

    $current_user = wp_get_current_user();
    update_blog_option( $blog_id, 'admin_email', $current_user->user_email );

This will overwrite whatever's happening during the sample-site-cloning process.

**Comment by patrickmj** [comment]
The phrase "you da man" was invented just for you. Thanks!

**Comment by amandafrench** [comment]
Thanks, both y'all. I should add that the GitHub repo here is now out of date with thatcamp.org on production, so be careful when pulling and pushing. When we moved to Reclaim I had some trouble with git, which I think is mostly worked out, but I've been lazily updating plugins from within the browser admin and stuff. Need to get them back in sync and make sure thatcampdev.info is as well, or possibly even get rid of thatcampdev.info and just assume that we'll all work from local versions.

**Comment by amandafrench** [comment]
I should also add that you're correct: this is default text in the THATCamp Registrations Settings in the Sample site at http://sample.thatcamp.org, which is the site that gets cloned in site generation. See screenshot. I'll edit that now to take it all out, so maybe no code necessary. But if there's some kind of shortcode for "admin_email" that I could put in there instead, that'd be awesome. 
![screenshot 2016-03-03 10 27 40](https://cloud.githubusercontent.com/assets/227453/13499112/dff3add6-e12a-11e5-8849-d761c4e9e202.png)

**Comment by amandafrench** [comment]
Here's revised text -- looking at it, I feel like there was some variable for [your current site] and such in there before at some point, but I've forgotten. In any case I've taken info@thatcamp.org out of the loop. 

![screenshot 2016-03-03 10 32 18](https://cloud.githubusercontent.com/assets/227453/13499231/5bba76d4-e12b-11e5-8f45-3893acfded81.png)

**Comment by patrickmj** [comment]
I suspect that the <strike>reason det</strike> <strike>raison d</strike> <strike>raisinette</strike> reason for existing for thatcampdev.info isn't there anymore. It made sense as a staging location to have the same server settings as production. Since that isn't true anymore since our move to Reclaim, I think working from our local installations might make more sense.

**Comment by amandafrench** [comment]
I'm going to close this issue, since it's basically fixed for new sites (though it will persist on old ones). @patrickmj, if you and Roberto want to take down the THATCamp dev server, go ahead.
